function createfigureBNRatio(X1, YMatrix1, X2, YMatrix2, X3, YMatrix3)
%CREATEFIGURE2(X1,YMATRIX1,X2,YMATRIX2,X3,YMATRIX3)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data
%  X2:  vector of x data
%  YMATRIX2:  matrix of y data
%  X3:  vector of x data
%  YMATRIX3:  matrix of y data
 
%  Auto-generated by MATLAB on 03-Apr-2012 16:20:10
 
% Create figure
figure1 = figure;
 
% Create axes
axes1 = axes('Parent',figure1,...
'XTick',[0 60 120 180 240 300 360 420 480 540 600 660 720 780 840 900 960 1020 1080 1140 1200],...
'Position',[0.13 0.09059 0.8419 0.8344]);
box('on');
hold('all');
 
% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',axes1,'Marker','*','LineStyle','-');
set(plot1(1),'Color',[1 0 1],'DisplayName','Egg');
set(plot1(2),'Color',[1 0 0],'DisplayName','Larva');
set(plot1(3),'DisplayName','Pupa','Color',[0 0 0]);
set(plot1(4),'Color',[0 1 0],'DisplayName','Nurse');
set(plot1(5),'Color',[0 0 1],'DisplayName','House');
set(plot1(6),'Color',[0 1 1],'DisplayName','Forager');
 
% Create multiple lines using matrix input to plot
plot2 = plot(X2,YMatrix2,'Parent',axes1,'Marker','*','LineStyle','-');
set(plot2(1),'Color',[1 0 1]);
set(plot2(2),'Color',[1 0 0]);
set(plot2(3),'Color',[0 0 0]);
set(plot2(4),'Color',[0 1 0]);
set(plot2(5),'Color',[0 0 1]);
set(plot2(6),'Color',[0 1 1]);
 
% Create multiple lines using matrix input to plot
plot3 = plot(X3,YMatrix3,'Parent',axes1,'Marker','*','LineStyle','-');
set(plot3(1),'Color',[1 0 1]);
set(plot3(2),'Color',[1 0 0]);
set(plot3(3),'Color',[0 0 0]);
set(plot3(4),'Color',[0 1 0]);
set(plot3(5),'Color',[0 0 1]);
set(plot3(6),'Color',[0 1 1]);
 
% Create legend
% legend1 = legend(axes1,'show');
% set(legend1,'Position',[-0.03384 0.2324 0.1025 0.5935]);
legend('Egg','Larva','Pupa','Nurse','House','Forager')
 
